; PlatformIO Project Configuration File
; Các dòng có dấu chấm phẩy là comment -> máy tính sẽ bỏ qua


[env:esp32doit-devkit-v1]                       ;Tên môi trường làm việc, thường được đặt theo tên mạch
platform = espressif32                          ;Nền tảng chip sử dụng là ESP32 của hãng espressif
board = esp32doit-devkit-v1                     ;Tên định danh chính xác của chip
framework = arduino                             ;Sử dụng framework có sẵn của arduino cho dễ viết
lib_deps = knolleary/PubSubClient@^2.8.0        ;Tự động set up thư viện cốt lõi giúp mạch giao tiếp với giao thức MQTT